[build]
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
