[build]
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
